services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        - HOST_DOCKER_GID=${HOST_DOCKER_GID}
    container_name: github-runner
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/home/github/_work:rw
    environment:
      - GH_REPO_URL=${GH_REPO_URL}
      - GH_RUNNER_TOKEN=${GH_RUNNER_TOKEN}
      - ACTIONS_RUNNER_HOOK_JOB_STARTED=/home/github/hooks/pre-job.sh

volumes:
  runner_data:
    name: runner_data
