---
- name: Inspect System
  hosts: archiso
  roles:
    - role: inspect
  tags:
    - always

- name: Clean System
  hosts: archiso
  roles:
    - role: clean
      when:
        - init is defined and init
  tags:
    - clean

- name: Provision Disks
  hosts: archiso
  roles:
    - role: provision_disks
      when:
        - init is defined and init
  tags:
    - provision_disks

- name: Prep System
  hosts: archiso
  roles:
    - role: prep_system
  tags:
    - always

- name: Install OS
  hosts: archiso
  roles:
    - role: install_os
      when:
        - init is defined and init
  tags:
    - install_os

- name: Configure System
  hosts: archiso
  roles:
    - role: configure_system
  tags:
    - configure_system

- name: Configure Network
  hosts: archiso
  roles:
    - role: configure_network
  tags:
    - configure_network

- name: Configure Bootloader
  hosts: archiso
  roles:
    - role: configure_bootloader
  tags:
    - configure_bootloader

- name: Complete Installation
  hosts: archiso
  roles:
    - role: complete_installation
  tags:
    - complete_installation
