server:
    module-config: "respip iterator"
    verbosity: 0
    interface: 0.0.0.0
    access-control: 0.0.0.0/0 allow
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    prefetch: no
    num-threads: 8
    cache-min-ttl: 3600
    cache-max-ttl: 86400
    rrset-roundrobin: yes
    minimal-responses: yes
    hide-identity: yes
    hide-version: yes
    use-syslog: no
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
    local-zone: "168.192.in-addr.arpa." transparent
    remote-control:
        control-enable: yes
        control-interface: 127.0.0.1
        control-port: 8953
        server-key-file: "/etc/unbound/unbound_server.key"
        server-cert-file: "/etc/unbound/unbound_server.pem"
        control-key-file: "/etc/unbound/unbound_control.key"
        control-cert-file: "/etc/unbound/unbound_control.pem"
#    rpz:
#        name: "blocklist.rpz.local."
#        zonefile: "/etc/unbound/rpz.blocklist.zone"
#        rpz-log: no

forward-zone:
    name: "."
    forward-addr: 1.1.1.1@853
    forward-addr: 1.0.0.1@853
    forward-tls-upstream: yes

auth-zone:
    name: "at.home."
    zonefile: "/etc/unbound/zones/at.home.zone"
    for-downstream: yes

auth-zone:
    name: "122.168.192.in-addr.arpa."
    zonefile: "/etc/unbound/zones/at.home.reverse.122.zone"
    for-downstream: yes

auth-zone:
    name: "123.168.192.in-addr.arpa."
    zonefile: "/etc/unbound/zones/at.home.reverse.123.zone"
    for-downstream: yes
