---
- name: Read system prep information
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../prep-system/defaults/main.yml"
  when:
    - bootstrap_dir is not defined

- name: Read disk provisioning information
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../provision-disks/defaults/main.yml"
  when:
    - root_dev is not defined or swap_dev is not defined or efi_dev is not defined

- name: Generate FSTAB
  ansible.builtin.shell:
    cmd: |
      genfstab -U {{ bootstrap_dir }} > {{ bootstrap_dir }}/etc/fstab

- name: Unmount Devices
  ansible.builtin.shell:
    cmd: |
      umount {{ bootstrap_dir }}/boot && \
      umount {{ bootstrap_dir }} && \
      swapoff {{ swap_dev }}

- name: Reboot system
  ansible.builtin.shell:
    cmd: |
      reboot
  when:
    - reboot
