---
- name: Configure Bootloader (Debian)
  when:
    - configure_bootloader_osname == "debian"
  environment:
    DEBIAN_FRONTEND: noninteractive
    PATH: /bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  block:
    - name: Configure Bootloader (Debian)
      ansible.builtin.include_tasks: configure_bootloader_debian.yml
