---
- name: Set LVM partition info
  ansible.builtin.set_fact:
    lvm_start_sector: "{{ (efi_start_sector | int) + (efi_sectors | int) | int }}"

- name: Partition the device
  ansible.builtin.shell:
    cmd: |
      echo "label: gpt" | sfdisk {{ installation_device }} && \
        echo "{{ efi_start_sector }} {{ efi_sectors }} U -" | sfdisk {{ installation_device }} --append && \
        echo "{{ lvm_start_sector }} - L -" | sfdisk {{ installation_device }} --append

- name: Format the EFI partition
  ansible.builtin.shell:
    cmd: |
      mkfs -t vfat {{ efi_dev }}

- name: Create physical volume
  ansible.builtin.shell:
    cmd: |
      pvcreate -f {{ installation_device }}2

- name: Create volume group
  ansible.builtin.shell:
    cmd: |
      vgcreate -f {{ vg_name }} {{ installation_device }}2

- name: Create logical volumes
  ansible.builtin.shell:
    cmd: |
      lvcreate -y -L {{ swap_size_bytes | int // 1024 // 1024 }}M -n {{ lv_swap_name }} {{ vg_name }} && \
      lvcreate -y -l 100%FREE -n {{ lv_root_name }} {{ vg_name }}

- name: Format the logical volumes
  ansible.builtin.shell:
    cmd: |
      mkswap {{ swap_dev }} && \
      mkfs -t ext4 -F {{ root_dev }}

- name: Execute partprobe
  ansible.builtin.shell:
    cmd: |
      partprobe {{ installation_device }}
  changed_when: false
