---
- name: Read system prep information
  ansible.builtin.include_vars:
    file: "{{ role_path }}/../prep-system/defaults/main.yml"
  when:
    - bootstrap_dir is not defined

- name: Install Base System
  block:
    - name: Bootstrap Debian
      ansible.builtin.include_tasks: bootstrap_debian.yml
  environment:
    DEBIAN_FRONTEND: noninteractive
    PATH: /bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
  when:
    - os_name == "debian"
