---
- name: Validate installation_device
  ansible.builtin.assert:
    that:
      - installation_device is defined
      - installation_device is match("^(\/dev\/[a-z]+)$")
    fail_msg: "The installation_device variable must be defined and match the pattern ^/dev/[a-z]+$"
    success_msg: "The installation_device variable is defined and matches the pattern ^/dev/[a-z]+$"

- name: Mount devices
  ansible.builtin.shell:
    cmd: |
      swapon {{ prep_system_swap_dev }} && \
      mount {{ prep_system_root_dev }} {{ prep_system_bootstrap_dir }} && \
      mkdir -pv {{ prep_system_bootstrap_dir }}/boot && \
      mount {{ prep_system_efi_dev }} {{ prep_system_bootstrap_dir }}/boot
  register: mount_result
  changed_when: mount_result.rc == 0
